# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  playcatalogservice:
    image: play.catalog
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GITHUB_PAT
    ports:
      - 5000:5000
    environment:
      - ServiceSettings__MessageBroker
      - MongoDbSettings__Host
      - MongoDbSettings__Port
      - MongoDbSettings__ConnectionString
      - RabbitMQSettings__Host
      - ServiceBusSettings__ConnectionString
      - IdentitySettings__AdminUserPassword
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - pe-network

networks:
  pe-network:
    external: true
    name: pe-network
    driver: bridge