apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: catalog-serviceaccount
      containers:
      - name: catalog
        image: playeconomy1384.azurecr.io/play.catalog:1.0.7
        env:
        - name: ServiceSettings__MessageBroker
          value: SERVICEBUS
        - name: ServiceSettings__KeyVaultName
          value: playeconomy1384
        - name: ServiceSettings__Authority
          value: https://playeconomy1384.northeurope.cloudapp.azure.com/identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: "/health/live"
            port: 5000
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/health/ready"
            port: 5000
          initialDelaySeconds: 10
          
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 5000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.identity/client-id: 75f94483-23ed-40f7-a0af-81533771aa30
  labels:
    azure.workload.identity/use: "true"
