microserviceName: catalog

image:
  repository: playeconomy1384.azurecr.io/play.catalog
  tag: 1.0.7

envVariables:
  IdentitySettings__PathBase: /catalog-svc
  ServiceSettings__Authority: https://playeconomy1384.northeurope.cloudapp.azure.com/identity-svc

resources:
  limits:
    memory: "256Mi"
    cpu: "200m"

container:
  port: 5000

serviceAccount:
  clientId: 75f94483-23ed-40f7-a0af-81533771aa30